version: '3'

volumes:
  postgres_data:
    driver: local

services:
  postgres:
    container_name: postgres-keycloak
    image: '${POSTGRES_IMAGE}:${POSTGRES_VERSION}'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${KEYCLOAK_DB}
      POSTGRES_USER: ${KEYCLOAK_DB_USER}
      POSTGRES_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
  keycloak:
    container_name: keycloak-bff
    image: '${KEYCLOAK_IMAGE}:${KEYCLOAK_VERSION}'
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres-keycloak
      DB_DATABASE: ${KEYCLOAK_DB}
      DB_USER: ${KEYCLOAK_DB_USER}
      DB_SCHEMA: public
      DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
      KEYCLOAK_USER: ${KEYCLOAK_USER}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
      KEYCLOAK_IMPORT: /config/onap-realm.json
    ports:
      - 8080:8080
    volumes:
      - ./config:/config
    depends_on:
      - postgres
  mongo-history:
    container_name: mongo-history
    image: '${MONGO_IMAGE}:${MONGO_VERSION}'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${HISTORY_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${HISTORY_PASSWORD}
  history:
    container_name: history
    image: '${IMAGE_REPOSITORY}/${HISTORY_IMAGE_NAME}:${HISTORY_IMAGE_TAG}'
    ports:
      - 9002:9002
    environment:
      HISTORY_USERNAME: ${HISTORY_USERNAME}
      HISTORY_PASSWORD: ${HISTORY_PASSWORD}
      HISTORY_DATABASE: ${HISTORY_DATABASE}
      KEYCLOAK_URL: ${KEYCLOAK_URL}
      KEYCLOAK_REALM: ${KEYCLOAK_REALM}
      MONGO_HOST: ${HISTORY_MONGO_HOST}
      MONGO_PORT: ${HISTORY_MONGO_PORT}
    depends_on:
      - mongo-history
  mongo-preferences:
    container_name: mongo-preferences
    image: '${MONGO_IMAGE}:${MONGO_VERSION}'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${PREFERENCES_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${PREFERENCES_PASSWORD}
  preferences:
    container_name: preferences
    image: '${IMAGE_REPOSITORY}/${PREFERENCES_IMAGE_NAME}:${PREFERENCES_IMAGE_TAG}'
    ports:
      - 9001:9001
    environment:
      PREFERENCES_USERNAME: ${PREFERENCES_USERNAME}
      PREFERENCES_PASSWORD: ${PREFERENCES_PASSWORD}
      PREFERENCES_DATABASE: ${PREFERENCES_DATABASE}
      KEYCLOAK_URL: ${KEYCLOAK_URL}
      KEYCLOAK_REALM: ${KEYCLOAK_REALM}
      MONGO_HOST: ${PREFERENCES_MONGO_HOST}
      MONGO_PORT: ${PREFERENCES_MONGO_PORT}
    depends_on:
      - mongo-preferences
  bff:
    container_name: bff
    image: '${IMAGE_REPOSITORY}/${BFF_IMAGE_NAME}:${BFF_IMAGE_TAG}'
    ports:
      - 9080:9080
    environment:
      KEYCLOAK_URL: ${KEYCLOAK_URL}
      KEYCLOAK_REALM: ${KEYCLOAK_REALM}
      KEYCLOAK_CLIENT_ID: ${KEYCLOAK_CLIENT_ID}
      KEYCLOAK_CLIENT_SECRET: ${KEYCLOAK_CLIENT_SECRET}
      PREFERENCES_URL: ${PREFERENCES_URL}
      HISTORY_URL: ${HISTORY_URL}
      COLLECTOR_HOST: localhost
      COLLECTOR_PORT: 9411
  # ui:
  #   container_name: ui
  #   image: "${IMAGE_REPOSITORY}/ui:latest"
  #   ports:
  #     - 80:8080
  #   environment:
  #     BFF_URL: ${BFF_URL}
  #     KEYCLOAK_HOSTNAME: http://localhost:8080
  #     KEYCLOAK_INTERNAL_URL: ${KEYCLOAK_URL}
  #     KEYCLOAK_REALM: ${KEYCLOAK_REALM}
  #     NGINX_PORT: 8080
  #     KEYCLOAK_CLIENT_ID: portal-app
