
POST http://localhost:8080/auth/realms/ONAP/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id=portal-app&client_secret=&scope=openid&grant_type=password&username=onap-admin&password=password
> {%
 client.global.set("access_token", response.body.access_token);
 client.global.set("id_token", response.body.id_token);
 %}

###

GET http://localhost:8080/auth/realms/ONAP/protocol/openid-connect/userinfo
Authorization: Bearer {{access_token}}
X-Auth-Identity: Bearer {{id_token}}

> {%
 client.global.set("user_id", response.body.sub);
 client.global.set("user_name", response.body.preferred_username);
 %}

###

POST http://localhost:9080/preferences
X-Request-Id: {{$uuid}}
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{access_token}}
X-Auth-Identity: Bearer {{id_token}}


{
  "properties": {
    "dashboard": {
      "apps": {
        "availableTiles": [
          {
            "type": "USER_LAST_ACTION_TILE",
            "displayed": false
          }
        ],
        "lastUserAction": {
          "interval": "1H",
          "filterType": "ALL"
        }
      }
    }
  }
}

###

GET http://localhost:9080/preferences
Accept: application/json
Authorization: Bearer {{access_token}}
X-Auth-Identity: Bearer {{id_token}}
X-Request-Id: {{$uuid}}

###

POST http://localhost:9080/actions/{{user_id}}
X-Request-Id: {{$uuid}}
Accept: application/json
Authorization: Bearer {{access_token}}
X-Auth-Identity: Bearer {{id_token}}
Content-Type: application/json

{
  "userId": "{{user_id}}",
  "actionCreatedAt": "{{$timestamp}}",
  "action": {
    "type": "DELETE",
    "entity": "USERADMINISTRATION",
    "entityParams": {
      "userName": "uli",
      "userId": "{{$randomInt}}"
    }
  }
}

###

GET http://localhost:9080/actions/{{user_id}}?page=1&pageSize=10&showLastHours=1
X-Request-Id: {{$uuid}}
Accept: application/json
Authorization: Bearer {{access_token}}
X-Auth-Identity: Bearer {{id_token}}

###

GET http://localhost:9080/actions?page=1&pageSize=10&showLastHours=1
X-Request-Id: {{$uuid}}
Accept: application/json
Authorization: Bearer {{access_token}}
X-Auth-Identity: Bearer {{id_token}}

### request agains portal-service

GET http://localhost:9080/key
X-Request-Id: {{$uuid}}
Accept: text/plain
Authorization: Bearer {{access_token}}
X-Auth-Identity: Bearer {{id_token}}

###

GET http://localhost:9080/key/{{user_name}}
X-Request-Id: {{$uuid}}
Accept: text/plain
Authorization: Bearer {{access_token}}
X-Auth-Identity: Bearer {{id_token}}

###

GET http://localhost:9080/tiles
X-Request-Id: {{$uuid}}
Accept: application/json
Authorization: Bearer {{access_token}}
X-Auth-Identity: Bearer {{id_token}}

###

GET http://localhost:9080/tiles/1
X-Request-Id: {{$uuid}}
Accept: application/json
Authorization: Bearer {{access_token}}
X-Auth-Identity: Bearer {{id_token}}

### request against keycloak

GET http://localhost:9080/users
X-Request-Id: {{$uuid}}
Accept: application/json
Authorization: Bearer {{access_token}}
X-Auth-Identity: Bearer {{id_token}}

###

GET http://localhost:9080/users/{{user_id}}
X-Request-Id: {{$uuid}}
Accept: application/json
Authorization: Bearer {{access_token}}
X-Auth-Identity: Bearer {{id_token}}

###

GET http://localhost:9080/users/{{user_id}}/roles
X-Request-Id: {{$uuid}}
Accept: application/json
Authorization: Bearer {{access_token}}
X-Auth-Identity: Bearer {{id_token}}

###
