---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2024 The Linux Foundation <https://linuxfoundation.org>

name: '🧱 Build Node.js Project'
# author: 'The Linux Foundation <https://linuxfoundation.org>'
# description: 'Build a Node.js project'

inputs:
  BUILD-TOOL:
    description: 'Used to build Node.js project [npm|yarn]'
    required: false
    default: 'npm'
  NODE-VERSION:
    description: 'Node.js version to use for build'
    required: false
    default: 20

runs:
  using: 'composite'

  steps:
    # Setup/install Node.js tooling
    - name: 'Setup Node.js'
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}

    # Build project with preferred tooling
    - shell: bash
      if: inputs.build-tool == 'yarn'
      run: |
        # Build project using NPM
        echo "Building project using NPM"
        echo "npm install --production"
        npm install --production
    - shell: bash
      if: inputs.build-tool == 'npm'
      run: |
        # Build project using Yarn
        echo "Building project using Yarn"
        echo "yarn install --prod"
        yarn install --prod
