---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2024 The Linux Foundation <https://linuxfoundation.org>

name: 'sonatype-lifecycle.yaml'
description: "Runs the Sonatype Lifecycle (Nexus IQ) scanning tool"

inputs:
  # Mandatory
  IQ-SERVER-URL:
    description: 'URL for Nexus IQ server'
    required: true
  USERNAME:
    description: 'Username for Nexus IQ server'
    required: true
  PASSWORD:
    description: 'Password for Nexus IQ server'
    required: true
  # NOT Mandatory
  SCAN-TARGETS:
    description: 'Location of code to scan'
    required: false
    type: string
    default: '.'
  JAVA-VERSION:
    description: 'Version of the Java runtime to use'
    required: false
    type: number
    default: 17
  IQ-CLI-VERSION:
    description: 'Version of the Nexus IQ CLI'
    required: false
    type: string
    default: '1.179.0-01'


secrets:
  NEXUS_IQ_PASSWORD:
    description: "Nexus IQ Password"
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup Sonatype CLI
      uses: sonatype/actions/setup-iq-cli@v1
      with:
        iq-cli-version: ${{ inputs.IQ-CLI-VERSION }}

    # Sonatype CLI requires Java to run
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: ${{ inputs.JAVA-VERSION }}

    # Run Sonatype CLI
    - name: Run Sonatype CLI
      uses: sonatype/actions/run-iq-cli@v1
      with:
        iq-server-url: ${{ inputs.IQ-SERVER-URL }}
        username: ${{ inputs.USERNAME }}
        password: ${{ inputs.PASSWORD }}
        # Temporary patch for testing
        application-id: onap-${{ github.event.repository.name }}
        # application-id: ${{ github.repository_owner }}-${{ github.event.repository.name }}
        scan-targets: ${{ inputs.SCAN-TARGETS }}
