---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2024 The Linux Foundation <https://linuxfoundation.org>

name: 'github-workflow.yaml'

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:

jobs:

  # Only runs when master repository is in Gerrit
  gerrit-node-verify-clm:
    uses: ModeSevenIndustrialSolutions/portal-ng-ui/.github/workflows/node-sonatype-lifecycle-releng.yaml@master
    secrets:
      NEXUS_IQ_PASSWORD: ${{ secrets.NEXUS_IQ_PASSWORD }}
