---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2024 The Linux Foundation <https://linuxfoundation.org>

name: 'Node Nexus IQ Scan [REUSABLE]'

# yamllint disable-line rule:truthy
on:
  workflow_call:
    inputs:
      BUILD-TOOL:
        description: 'Used to build Node.js project [npm|yarn]'
        required: false
        type: string
        default: 'yarn'
      NODE-VERSION:
        description: 'Node.js version to use for build'
        required: false
        type: number
        default: 20
      LOCATION:
        description: 'Location of source repository'
        required: false
        type: string
        # Origin could [potentially be: [gerrit|github|gitlab]
        default: "github"

jobs:

  node-verify-clm:
    name: "Scan Node.js project with Nexus IQ"
    runs-on: ubuntu-latest
    steps:

      - name: "Checkout repository if source is GitHub"
        if: inputs.location == 'github'

      - name: "Build Node.js project"
        uses: ModeSevenIndustrialSolutions/portal-ng-ui/.github/actions/node-build@master
        with:
          node-version: ${{ inputs.node-version }}
          build-tool: ${{ inputs.build-tool }}

      - name: Nexus IQ Policy Evaluation
        # Somebody has set continue-on-error in the RelEng Reusable Workflows Repository
        # continue-on-error: true
        # Why?!?!?
        # yamllint disable-line rule:line-length
        # See: https://github.com/lfit/releng-reusable-workflows/blob/main/.github/workflows/composed-gradle-nexus-iq.yaml
        # yamllint disable-line rule:line-length
        # See: https://github.com/lfit/releng-reusable-workflows/blob/main/.github/workflows/composed-maven-nexus-iq.yaml
        # This has an issue with the shebang directive:
        # uses: sonatype-nexus-community/iq-github-action@main
        # See: https://github.com/onap/portal-ng-ui/actions/runs/10527123076/job/29169584344
        # e.g. /entrypoint.sh: 18: [[: not found
        uses: ModeSevenIndustrialSolutions/portal-ng-ui/.github/actions/iq-github-action@master
        with:
          serverUrl: ${{ vars.NEXUS_IQ_SERVER }}
          username: ${{ vars.NEXUS_IQ_USERNAME }}
          password: ${{ secrets.NEXUS_IQ_PASSWORD }}
          # Temporarily force to ONAP because testing in ModeSevenIndustrialSolutions
          applicationId: onap-${{ github.event.repository.name }}
          # applicationId: ${{ github.repository_owner }}-${{ github.event.repository.name }}
          stage: 'build'
          writePolicyEvaluationJson: 'policy-eval-results.json'
          # target: ''
          # debug: true
