---
name: SonarCloud analysis

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
    inputs:
      GERRIT_BRANCH:
        description: "Branch that change is against"
        required: true
        type: string
      GERRIT_CHANGE_ID:
        description: "The ID for the change"
        required: true
        type: string
      GERRIT_CHANGE_NUMBER:
        description: "The Gerrit number"
        required: true
        type: string
      GERRIT_CHANGE_URL:
        description: "URL to the change"
        required: true
        type: string
      GERRIT_EVENT_TYPE:
        description: "Type of Gerrit event"
        required: true
        type: string
      GERRIT_PATCHSET_NUMBER:
        description: "The patch number for the change"
        required: true
        type: string
      GERRIT_PATCHSET_REVISION:
        description: "The revision sha"
        required: true
        type: string
      GERRIT_PROJECT:
        description: "Project in Gerrit"
        required: true
        type: string
      GERRIT_REFSPEC:
        description: "Gerrit refspec of change"
        required: true
        type: string

jobs:
  Analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Run Sonar Cloud scan
        uses: lfit/releng-reusable-workflows/.github/workflows/composed-generic-sonar-cloud.yaml@main
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          SONAR_ARGS: >
            -Dsonar.organization=o-ran-sc
            -Dsonar.projectKey=o-ran-sc_portal-ng-ui
            -Dsonar.projectName=portal-ng-ui
            -Dsonar.build.sourceEncoding=UTF-8
            -Dsonar.sources=.
            -Dsonar.go.coverage.reportPaths=**/cover.out
            -Dsonar.verbose=true
